sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - grunt build
  - cp test/config.js.travis-ci test/config.js
script: node test/node-runner.js
